@baseUrl1 = http://localhost:5108
@baseUrl2 = https://localhost:7248



@studentNumber = R2024-02383
@studentPassword = password123
@studentRole = student
### Register for student
POST {{baseUrl1}}/api/auth/register
Content-Type: application/json

{
    "studentNumber": "{{studentNumber}}", 
    "password": "{{studentPassword}}",
    "role": "{{studentRole}}"
}

###
@facultyUsername = appuser123
@facultyPassword = password123
@facultyRole = faculty
### Register for faculty
POST {{baseUrl1}}/api/auth/register
Content-Type: application/json

{
    "username": "{{facultyUsername}}", 
    "password": "{{facultyPassword}}",
    "role": "{{facultyRole}}"
}



### Login for student
# @name loginStudent
POST {{baseUrl1}}/api/auth/login
Content-Type: application/json 

{
    "studentNumber": "{{studentNumber}}",
    "password": "{{studentPassword}}"
}



### Login for faculty
# @name loginFaculty
POST {{baseUrl1}}/api/auth/login
Content-Type: application/json 

{
    "username": "{{facultyUsername}}",
    "password": "{{facultyPassword}}"
}


###
@accessToken = {{loginStudent.response.body.data.accessToken}}
@refreshToken = {{loginStudent.response.body.data.refreshToken}}
@accessToken = {{loginFaculty.response.body.data.accessToken}}
@refreshToken = {{loginFaculty.response.body.data.refreshToken}}


### Refresh Token
POST {{baseUrl1}}/api/auth/refresh
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "refreshToken": "{{refreshToken}}"
}



### Logout
POST {{baseUrl1}}/api/auth/logout
Content-Type: application/json
Authorization: Bearer {{accessToken}}
