@baseUrl1 = http://localhost:5108
@baseUrl2 = https://localhost:7248
@accessToken = {{login.response.body.data.accessToken}}
@refreshToken = {{login.response.body.data.refreshToken}}
@testUsername = appuser123
@testPassword = password123
@testRole = student

### Get access token
POST {{baseUrl1}}/api/auth/login
Content-Type: application/json 

{
    "username": "{{testUsername}}",
    "password": "{{testPassword}}"
}


### Get user's notifications
GET {{baseUrl1}}/api/notification
Authorization: Bearer {{accessToken}}

### Mark as read
POST {{baseUrl1}}/api/notification/{{notificationId}}/mark-as-read
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
