@baseUrl1 = http://localhost:5108
@baseUrl2 = https://localhost:7248

### ------------------------------------------------------
### Get access token
@testUsername = prof.aguilar123
@testPassword = password123
# @name login
POST {{baseUrl1}}/api/auth/login
Content-Type: application/json

{
    "username": "{{testUsername}}",
    "password": "{{testPassword}}"
}


### ------------------------------------------------------
### Store tokens
@accessToken = {{login.response.body.data.accessToken}}
@refreshToken = {{login.response.body.data.refreshToken}}


### ------------------------------------------------------
### Get all venues
GET {{baseUrl1}}/api/venues
Authorization: Bearer {{accessToken}}


### ------------------------------------------------------
### Get venues with filter
@testStatus = available
GET {{baseUrl1}}/api/venues?status={{testStatus}}
Authorization: Bearer {{accessToken}}


### ------------------------------------------------------
### Create venue
# @name createVenue
POST {{baseUrl1}}/api/venues
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Chapel Hall
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="address"

St. Placid Chapel
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="capacity"

300
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Ideal for religious ceremonies, symphonies, and large gatherings.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="availability"

Mon - Sat
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="timeslots"

8:00 - 11:00
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="timeslots"

13:00 - 15:00
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="timeslots"

16:00 - 17:00
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="photoCover"; filename="sampol.jpg"
Content-Type: image/jpeg

< ./test_files/sampol.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### ------------------------------------------------------
### Update venue's status
@venueStatus = approved
@venueReason = null
@venueId = 1
PATCH {{baseUrl1}}/api/venues/{{venueId}}/status
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "status": "{{venueStatus}}",
    "reason": "{{venueReason}}"
}
